services:
  # Serviço de Banco de Dados (Postgres 16)
  db:
    image: postgres:16
    container_name: sergipetec-db
    environment:
      POSTGRES_DB: sergipetec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Executa o init.sql ao iniciar o banco pela primeira vez
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Serviço da API Java
  app:
    build: .
    container_name: sergipetec-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Conecta no container 'db'
      # stringtype=unspecified é OBRIGATÓRIO para seu Enum funcionar
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sergipetec?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: